# Python stubs generated by omniidl from idl/SpeechConsumer.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Consumer"
#
__name__ = "Consumer"
_0_Consumer = omniORB.openModule("Consumer", r"idl/SpeechConsumer.idl")
_0_Consumer__POA = omniORB.openModule("Consumer__POA", r"idl/SpeechConsumer.idl")


# interface SpeechConsumer
_0_Consumer._d_SpeechConsumer = (omniORB.tcInternal.tv_objref, "IDL:Consumer/SpeechConsumer:1.0", "SpeechConsumer")
omniORB.typeMapping["IDL:Consumer/SpeechConsumer:1.0"] = _0_Consumer._d_SpeechConsumer
_0_Consumer.SpeechConsumer = omniORB.newEmptyClass()
class SpeechConsumer :
    _NP_RepositoryId = _0_Consumer._d_SpeechConsumer[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Consumer.SpeechConsumer = SpeechConsumer
_0_Consumer._tc_SpeechConsumer = omniORB.tcInternal.createTypeCode(_0_Consumer._d_SpeechConsumer)
omniORB.registerType(SpeechConsumer._NP_RepositoryId, _0_Consumer._d_SpeechConsumer, _0_Consumer._tc_SpeechConsumer)

# SpeechConsumer operations and attributes
SpeechConsumer._d_write = (((omniORB.tcInternal.tv_string,0), ), (), None)

# SpeechConsumer object reference
class _objref_SpeechConsumer (CORBA.Object):
    _NP_RepositoryId = SpeechConsumer._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def write(self, *args):
        return self._obj.invoke("write", _0_Consumer.SpeechConsumer._d_write, args)

omniORB.registerObjref(SpeechConsumer._NP_RepositoryId, _objref_SpeechConsumer)
_0_Consumer._objref_SpeechConsumer = _objref_SpeechConsumer
del SpeechConsumer, _objref_SpeechConsumer

# SpeechConsumer skeleton
__name__ = "Consumer__POA"
class SpeechConsumer (PortableServer.Servant):
    _NP_RepositoryId = _0_Consumer.SpeechConsumer._NP_RepositoryId


    _omni_op_d = {"write": _0_Consumer.SpeechConsumer._d_write}

SpeechConsumer._omni_skeleton = SpeechConsumer
_0_Consumer__POA.SpeechConsumer = SpeechConsumer
omniORB.registerSkeleton(SpeechConsumer._NP_RepositoryId, SpeechConsumer)
del SpeechConsumer
__name__ = "Consumer"

#
# End of module "Consumer"
#
__name__ = "SpeechConsumer_idl"

_exported_modules = ( "Consumer", )

# The end.
