# DO NOT EDIT THIS FILE!
#
# Python module Consumer generated by omniidl

import omniORB
omniORB.updateModule("Consumer")

# ** 1. Stub files contributing to this module
import SpeechConsumer_idl

# ** 2. Sub-modules

# ** 3. End
