# DO NOT EDIT THIS FILE!
#
# Python module Provider generated by omniidl

import omniORB
omniORB.updateModule("Provider")

# ** 1. Stub files contributing to this module
import SpeechProvider_idl

# ** 2. Sub-modules

# ** 3. End
